### ISSUE TITLE
pyramid.httpexceptions:HTTPConflict: There was a conflict when trying to complete your request

### ISSUE THREAD

**Issue by tarekziade** [mozilla-services/cliquet#185]
Seen on New Relic on high load:

```python
Traceback (most recent call last):
File "/data/readinglist/lib/python2.7/site-packages/newrelic-2.48.0.38/newrelic/api/web_transaction.py", line 711, in __iter__
File "/data/readinglist/lib/python2.7/site-packages/newrelic-2.48.0.38/newrelic/api/web_transaction.py", line 1087, in __call__
File "/data/readinglist/lib/python2.7/site-packages/newrelic-2.48.0.38/newrelic/api/web_transaction.py", line 1215, in _nr_wsgi_application_wrapper_
File "/data/readinglist/lib/python2.7/site-packages/pyramid/router.py", line 242, in __call__
File "/data/readinglist/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
File "/data/readinglist/lib/python2.7/site-packages/cliquet/__init__.py", line 221, in eos_tween
File "/data/readinglist/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
File "/data/readinglist/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
File "/data/readinglist/lib/python2.7/site-packages/newrelic-2.48.0.38/newrelic/hooks/framework_pyramid.py", line 85, in view_handler_wrapper
File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 245, in _secured_view
File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
File "/data/readinglist/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
File "/data/readinglist/lib/python2.7/site-packages/cornice/service.py", line 548, in wrapper
File "/data/readinglist/lib/python2.7/site-packages/cliquet/resource.py", line 204, in patch
File "./readinglist/views/article.py", line 136, in update_record
File "/data/readinglist/lib/python2.7/site-packages/cliquet/resource.py", line 339, in update_record
File "/data/readinglist/lib/python2.7/site-packages/cliquet/resource.py", line 500, in _raise_conflict
```

**Comment by tarekziade** [comment]
dupe of https://github.com/mozilla-services/cliquet/issues/185
