### ISSUE TITLE
KeyError with bad request (content type)

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#310]
Using this 
```python
self.session.put(bucket_url,
                             {'data': {}},
                             auth=self.auth,
                             headers={'If-None-Match': '*'})
```

I had this:
```
2015-06-15 12:23:22,974 INFO  [venusian][Dummy-5] "PUT   /v1/buckets/43904d5519954d59a374660a947d0922" 400 (6 ms) request.summary lang=None; uid=basicauth_0062631f0e1551bde4e4fc5977188122e17253f6517e4cb95528f313ea92aaa6; errno=107; agent=python-requests/2.7.0 CPython/2.7.9 Linux/3.19.0-20-generic; authn_type=BasicAuth; time=2015-06-15T12:23:22; collection_id=bucket; collection_timestamp=1434363802970
2015-06-15 12:23:22,975 ERROR [venusian][Dummy-2] "      " ? (? ms) '/{path:(?!v1).*}' lang=None; exception=Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/mathieu/Code/Mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 118, in handle_request
    root = root_factory(request)
  File "/home/mathieu/Code/Mozilla/cliquet/cliquet/authorization.py", line 48, in __init__
    service = utils.current_service(request)
  File "/home/mathieu/Code/Mozilla/cliquet/cliquet/utils.py", line 126, in current_service
    service = services[pattern]
KeyError: '/{path:(?!v1).*}'; uid=None; errno=None; agent=None; authn_type=None
```

Could fix from client with right content type:
```python
            self.session.put(bucket_url,
                             data=json.dumps({'data': {}}),
                             auth=self.auth,
                             headers={'If-None-Match': '*',
                                      'Content-Type': 'application/json'})
```

**Comment by Natim** [comment]
I can reproduce by doing:

    make runkinto
    http GET http://localhost:8888/v0/buckets --auth=admin:

**Comment by Natim** [comment]
Actually the bug is that v0 is not recognize so we handler the match all route that does a 307 and is not registered as a service.
