### ISSUE TITLE
Invalid JSON raises 500 on record PATCH

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#373]
Following code (I know it's bad):
```python
data = json.dumps(data)
resp = self.session.patch(url, {'data': data}, auth=self.auth)
```

Makes the server fail:
```
12:20:05,742 ERROR [venusian] "PATCH /v1/articles/543212c6-f9bd-4379-af3f-d1ec5ebc408e" ? (? ms) Expected object or value lang=None; exception=Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/cornice/service.py", line 567, in wrapper
    response = view_()
  File "/home/mathieu/Code/Mozilla/cliquet/cliquet/resource.py", line 567, in patch
    changes = self.request.json.get('data', {})  # May patch only perms.
  File "/home/mathieu/Code/Mozilla/readinglist/.venv/local/lib/python2.7/site-packages/webob/request.py", line 725, in _json_body__get
    return json.loads(self.body.decode(self.charset))
ValueError: Expected object or value; uid=8c24c4168eb99e1390ebfc1daac05fae7d213c82cfd284fcc00e4446f6c566a7; errno=None; agent=python-requests/2.6.0 CPython/2.7.8 Linux/3.19.0-22-generic; authn_type=BasicAuth; collection_id=article; collection_timestamp=1436523605714

```

**Comment by Natim** [comment]
As far as I can tell, it seems to have been fixed in Kinto 1.4.0:

```
>>> import json
>>> import requests
>>> data = {"success": True}
>>> data = json.dumps(data)
>>> requests.patch("https://kinto.dev.mozaws.net/v1/buckets/default/collections/tasks", {"data": data}, auth=("natim", ""))
<Response [400]>
>>> resp = requests.patch("https://kinto.dev.mozaws.net/v1/buckets/default/collections/tasks", {"data": data}, auth=("natim", ""))
resp>>> resp.json()
{u'errno': 107, u'message': u'data in body: "{"success": true}" is not a mapping type: Does not implement dict-like functionality.', u'code': 400, u'details': [{u'description': u'"{"success": true}" is not a mapping type: Does not implement dict-like functionality.', u'location': u'body', u'name': u'data'}], u'error': u'Invalid parameters'}
```
