### ISSUE TITLE
AttributeError: 'Registry' object has no attribute 'storage'

### ISSUE THREAD

**Issue by MrChoclate** [mozilla-services/cliquet#538]
I ran into this error message when I did  ```http -v http://localhost:6543/v0/champions --auth user:pass```

```
(env)[choclate@choclate contest]$ pserve development.ini --reload
Starting subprocess with file monitor
2015-11-02 23:39:57,102 INFO  [venusian][MainThread] contest 0.0 starting. 
Starting server in PID 4651.
serving on http://0.0.0.0:6543
2015-11-02 23:39:59,033 ERROR [venusian][waitress] "GET   /v0/champions" ? (? ms) 'Registry' object has no attribute 'storage' authn_type=BasicAuth; lang=None; uid=5741b99cc5b467903f9a392b092d59f6d227354acbca1834bdd1dea1dd350a8e; agent=HTTPie/0.9.2; exception=Traceback (most recent call last):
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/pyramid/config/views.py", line 245, in _secured_view
    return view(context, request)
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)h
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/cornice/service.py", line 541, in wrapper
    ob = args['klass'](**params)
  File "/home/choclate/documents/projects/web/contest/env/lib/python3.5/site-packages/cliquet/resource/__init__.py", line 139, in __init__
    storage=request.registry.storage,
AttributeError: 'Registry' object has no attribute 'storage'; errno=None
2015-11-02 23:39:59,034 INFO  [venusian][waitress] "GET   /v0/champions" 500 (2 ms) request.summary authn_type=BasicAuth; lang=None; uid=5741b99cc5b467903f9a392b092d59f6d227354acbca1834bdd1dea1dd350a8e; agent=HTTPie/0.9.2; time=2015-11-02T23:39:59.033999; errno=999
```

This is a very small app with only one ressource and one schema. Last time I tried to used cliquet everything was fine. Is there a problem if I use virtualenv? There is no use of virtualenv in the doc, but it should be ok, right?  

I tried to add ```cliquet.storage_backend = cliquet.storage.memory``` in development.ini. I also tried to use python3.4.

The source code is available here: https://github.com/Atilla106/contest

Any ideas?

**Comment by leplatrem** [comment]
Oh nice catch!

That's definitely because you omitted the `cliquet.storage_backend` from your config, or it is not taken into account for some reason.

A while ago, we used to define a default storage backend, even if it was not used.

I still mark this as bug, because I would take the opportunity of this feedback, to implement a safety check : if a resource is used, then fail to start the application with a message saying that no storage backend is configured :)

Thanks !

**Comment by MrChoclate** [comment]
Well, it was not taken into account because it has to be after ```[app:main]```. I never used Pyramid before so I added it at the end of the ini file. Was a mistake.

I can close the issue or maybe you want to ref it for a future test?
