### ISSUE TITLE
UnicodeEncodeError on PUT /buckets/見 with Redis backend.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#556]
See http://sentry.notmyidea.org/sentry/kinto-dev/group/40/ for details

```
"PUT   /v1/buckets/%E8%A6%8B" ? (? ms) 'ascii' codec can't encode character u'\u898b' in position 0: ordinal not in range(128) lang=None; exception=Traceback (most recent call last):
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/router.py", line 118, in handle_request
    root = root_factory(request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/authorization.py", line 117, in __init__
    record = resource.model.get_record(resource.record_id)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/resource/model.py", line 272, in get_record
    record = super(ProtectedModel, self).get_record(record_id, parent_id)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/resource/model.py", line 141, in get_record
    auth=self.auth)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/storage/redis.py", line 18, in wrapped
    return func(*args, **kwargs)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/storage/redis.py", line 134, in get
    object_id)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u898b' in position 0: ordinal not in range(128);
```

**Comment by leplatrem** [comment]
Duplicated of #557 ?

**Comment by Natim** [comment]
One is to fix Postgresql the other one for Redis, but yes maybe we can close both with the same PR.

**Comment by leplatrem** [comment]
No prob to have two issues!

**Comment by leplatrem** [comment]
could not reproduce with:

```diff
--- a/cliquet/tests/test_permission.py
+++ b/cliquet/tests/test_permission.py
@@ -1,3 +1,4 @@
+# -*- coding: utf-8 -*-
 import mock
 
 import redis
@@ -212,6 +213,24 @@ class BaseTestPermission(object):
             object_id, permission, {principal})
         self.assertTrue(check_permission)
 
+    def test_check_permission_supports_unicode_ids(self):
+        object_id = u'Rémy'
+        permission = 'write'
+        group_id = u'baré'
+        user_id = 'foobar'
+        self.permission.check_permission(
+            object_id, permission, {user_id, group_id})
+
+    def test_check_permission_supports_bound_permissions_with_unicode(self):
+        object_id = u'Rémy'
+        permission = 'write'
+        group_id = u'baré'
+        user_id = 'foobar'
+
+        self.permission.check_permission(
+            object_id, permission, {user_id, group_id},
+            get_bound_permissions=lambda obj, p: [(u'/buckets/見', 'read')])
+
```
