### ISSUE TITLE
Storage backends fail with unicode (parent) IDs

### ISSUE THREAD

**Issue by Natim** [mozilla-services/cliquet#557]
```
2015-11-05 15:20:55,920 ERROR [venusian][waitress] "GET   /v1/buckets/b4f6b878-44c5-dbdc-25e0-66e36e1673d0/collections/%E8%A6%8B/records" ? (? ms) 'dict' object does not support indexing lang=None; exception=Traceback (most recent call last):
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "~/mozilla/kinto/kinto/views/buckets.py", line 169, in default_bucket
    response = request.invoke_subrequest(subrequest)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 243, in _secured_view
    result = _permitted(context, request)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/pyramid/config/views.py", line 241, in _permitted
    permission)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/cliquet/authorization.py", line 50, in permits
    get_bound_permissions=self.get_bound_permissions)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/cliquet/authorization.py", line 143, in check_permission
    return self._check_permission(self.permission_object_id, *args, **kw)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/cliquet/permission/postgresql/__init__.py", line 247, in check_permission
    result = conn.execute(query)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "~/mozilla/kinto/.venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
TypeError: 'dict' object does not support indexing;
```

**Comment by leplatrem** [comment]
Isn't it supposed to be catched by name generator id validator ?

**Comment by Natim** [comment]
> Isn't it supposed to be catched by name generator id validator ?

This is true and it is the subject of bug https://github.com/Kinto/kinto/issues/260 also in case the ID validator allow for unicode character it should not raise at the storage level.

**Comment by leplatrem** [comment]
This does not prevent us from safety check on the cliquet side.

By the way, the problem exists for Redis too:

```
"PUT   /v1/buckets/%E8%A6%8B" ? (? ms) 'ascii' codec can't encode character u'\u898b' in position 0: ordinal not in range(128) lang=None; exception=Traceback (most recent call last):
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/pyramid/router.py", line 118, in handle_request
    root = root_factory(request)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/authorization.py", line 117, in __init__
    record = resource.model.get_record(resource.record_id)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/resource/model.py", line 272, in get_record
    record = super(ProtectedModel, self).get_record(record_id, parent_id)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/resource/model.py", line 141, in get_record
    auth=self.auth)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/storage/redis.py", line 18, in wrapped
    return func(*args, **kwargs)
  File "/home/ubuntu/venvs/kinto/local/lib/python2.7/site-packages/cliquet/storage/redis.py", line 134, in get
    object_id)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u898b' in position 0: ordinal not in range(128); uid=df93ca0ecaeaa3126595f6785b39c408be2539173c991a7b2e3181a9826a69bc; errno=None; agent=HTTPie/0.9.2; authn_type=BasicAuth; collection_id=bucket; collection_timestamp=1446731499566
```

**Comment by leplatrem** [comment]
The stacktrace provided in your initial comment is unrelated to the unicode error of Redis.

**Comment by leplatrem** [comment]
I would be in favor of closing this issue

**Comment by Natim** [comment]
I didn't know you couldn't reproduce the issue. Here are the step I follow to reproduce.

1. Configure kinto.ini with PostgreSQL and UWSGI.

```
[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 8888


[app:main]
use = egg:kinto

kinto.flush_endpoint_enabled = true

#
# Backends.
#
# http://kinto.readthedocs.org/en/latest/configuration/settings.html#storage
#
# kinto.storage_backend = cliquet.storage.redis
# kinto.storage_url = redis://localhos:6379/1
# kinto.cache_backend = cliquet.cache.redis
# kinto.cache_url = redis://localhos:6379/2
# kinto.permission_backend = cliquet.permission.redis
# kinto.permission_url = redis://localhos:6379/3

kinto.cache_backend = cliquet.cache.postgresql
kinto.cache_url = postgres://postgres:postgres@localhost:5432/postgres
kinto.storage_backend = cliquet.storage.postgresql
kinto.storage_url = postgres://postgres:postgres@localhost:5432/postgres
kinto.permission_backend = cliquet.permission.postgresql
kinto.permission_url = postgres://postgres:postgres@localhost:5432/postgres
kinto.userid_hmac_secret = b4c96a8692291d88fe5a97dd91846eb4


#
# Auth configuration.
#
# http://kinto.readthedocs.org/en/latest/configuration/settings.html#authentication
#
kinto.userid_hmac_secret = XXX-replace-by-a-secret-phrase-XXX
multiauth.policies = basicauth
# multiauth.policies = fxa basicauth

# kinto.bucket_create_principals = system.Authenticated
# kinto.batch_max_requests = 25

#
# Experimental JSON-schema on collection
# kinto.experimental_collection_schema_validation = true

#
# Firefox Accounts configuration.
#   These are working FxA credentials for localhost:8888
# kinto.includes  = cliquet_fxa
# fxa-oauth.client_id = 61c3f791f740c19a
# fxa-oauth.client_secret = b13739d8a905315314b09fb7b947aaeb62b47c6a4a5efb00c378fdecacd1e95e
# fxa-oauth.oauth_uri = https://oauth-stable.dev.lcip.org/v1
# fxa-oauth.requested_scope = profile kinto
# fxa-oauth.required_scope = kinto
# fxa-oauth.relier.enabled = true
# fxa-oauth.webapp.authorized_domains = *

#
# Client cache headers
#
# http://kinto.readthedocs.org/en/latest/configuration/settings.html#client-caching
#
# Every bucket objects objects and list
# kinto.bucket_cache_expires_seconds = 3600
#
# Every collection objects and list of every buckets
# kinto.collection_cache_expires_seconds = 3600
#
# Every group objects and list of every buckets
# kinto.group_cache_expires_seconds = 3600
#
# Every records objects and list of every collections
# kinto.record_cache_expires_seconds = 3600
#
# Records in a specific bucket
# kinto.blog_record_cache_expires_seconds = 3600
#
# Records in a specific collection in a specific bucket
# kinto.blog_article_record_cache_expires_seconds = 3600

#
# Production settings
#
# http://kinto.readthedocs.org/en/latest/configuration/production.html
#
# kinto.statsd_url = udp://localhost:8125
# kinto.statsd_prefix = kinto-prod

# kinto.http_scheme = https
# kinto.http_host = kinto.services.mozilla.com

# kinto.backoff = 10
# kinto.retry_after_seconds = 30
# kinto.eos =


[uwsgi]
wsgi-file = app.wsgi
enable-threads = true
http = 0.0.0.0:8888
processes =  3
master = true
module = kinto
harakiri = 120
uid = kinto
gid = kinto
virtualenv = .venv
lazy = true
lazy-apps = true
single-interpreter = true
buffer-size = 65535
post-buffering = 65535


#
# Logging configuration
#

# kinto.logging_renderer = cliquet.logs.ClassicLogRenderer

[loggers]
keys = root, cliquet

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console

[logger_cliquet]
level = DEBUG
handlers =
qualname = cliquet

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s

# End logging configuration
```

2. Access: http://localhost:8888/v1/buckets/default/collections/%E8%A6%8B/records

**Comment by Natim** [comment]
It works with kinto and current cliquet (both on the master branch)
