### ISSUE TITLE
Error when triggering event from service nested in resource

### ISSUE THREAD

**Issue by leplatrem** [mozilla-services/cliquet#625]
```
2016-01-19 10:53:35,700 ERROR [cliquet.initialization][waitress] "POST  /v1/buckets/b3cd54a6-9e43-10eb-2833-f3ba194e0786/collections/assets/records/c2ce1975-0e52-4b2f-a5db-80166aeca689/attachment" ? (? ms) Unable to notify lang=None; exception=Traceback (most recent call last):
  File "/home/mathieu/Code/Mozilla/cliquet/cliquet/resource/__init__.py", line 658, in _notify_event
    event = event_cls(action, self, impacted, self.request)
  File "/home/mathieu/Code/Mozilla/cliquet/cliquet/events.py", line 34, in __init__
    super(ResourceRead, self).__init__(action, resource, request)
  File "/home/mathieu/Code/Mozilla/cliquet/cliquet/events.py", line 14, in __init__
    resource_name = service.viewset.get_name(resource.__class__)
AttributeError: 'Service' object has no attribute 'viewset'; uid=f8d1e543ccf5d0bdb3ce8
```

This happens when black magic is employed to trigger action on resources manually: https://github.com/Kinto/kinto-attachment/blob/0.2.0/kinto_attachment/views.py#L85-L109

**Comment by leplatrem** [comment]
Could not reproduce
